djangoapp/urls.py
from django.urls import path
from djangoapp import views

urlpatterns = [
    path('',views.home,name = 'home'),
    path('computer_entry',views.computer_entry,name = 'computer_entry'),
    path('computer_list',views.computer_list,name = 'computer_list'),
    path('update/<pk>',views.computer_list_update,name = 'computer_list_update'),
    path('delete/<pk>',views.computer_list_delete,name = 'computer_list_delete'),
    path('register',views.registration_view,name = 'register'),
    path('login',views.loginpage_view,name = 'login'),
    path('logout',views.logoutpage_view,name = 'logout'),
    path('computer_history_list',views.computer_history_list, name='computer_history_list'),
    path('historydelete/<id>',views.computer_history_list_delete, name='history_delete'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from djangoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('djangoapp.urls'))
]

djangoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# class Operating_system(models.Model):
#     operating_system = models.CharField(max_length=30, blank=True)
#
#     def __str__(self):
#         return self.operating_system

class Computer(models.Model):
    computer_name = models.CharField(max_length=100,blank=True)
    IP_address = models.CharField(max_length=100)
    MAC_address = models.CharField(max_length=100,blank=True)
    # operating_system = models.ForeignKey(Operating_system,on_delete=models.CASCADE, blank=True, null=True)
    users_name = models.CharField(max_length=100,blank=True)
    location = models.CharField(max_length=100,blank=True)
    price = models.CharField(max_length=100,blank=True,null=True)
    purchase_date = models.DateTimeField('purchase Date(dd/mm/2020)',auto_now_add=False,auto_now=False,blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False,blank=True)
    export_to_CSV = models.BooleanField(default=False)

    def __unicode__(self):
        return self.computer_name


class ComputerHistory(models.Model):
    computer_name = models.CharField(max_length=100, blank=True, null=True)
    IP_address = models.CharField(max_length=100, blank=True, null=True)
    MAC_address = models.CharField(max_length=30, blank=True, null=True)
    users_name = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    purchase_date = models.DateField("Purchase Date(mm/dd/2019)", auto_now_add=False, auto_now=False, blank=True,
                                     null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False, blank=True, null=True)

djangoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from djangoapp.models import Computer
class ComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = '__all__'

    # def clean_computer_name(self):
    #     computer_name = self.cleaned_data.get('computer_name')
    #     if(computer_name == ''):
    #         raise forms.ValidationError("This Filed Cannot be Left Blank")
    #     return computer_name
    #
    # def clean_IP_address(self):
    #     IP_address = self.cleaned_data.get('IP_address')
    #     if (IP_address == ''):
    #         raise forms.ValidationError("This Filed Cannot be Left Blank")
    #     return IP_address

class ComputerSearchForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ['computer_name','users_name','export_to_CSV']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2']

djangoapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from djangoapp.forms import ComputerForm, ComputerSearchForm, CreateUserForm
from djangoapp.models import Computer,ComputerHistory
from  django.contrib.auth import authenticate,login,logout
import csv
def home(request):
    title = "welcome to India"
    context = {'title':title}
    return render(request,'base.html',context)
@login_required(login_url='login')
def computer_entry(request):
    if request.method == 'POST':
        form = ComputerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Successfully Data Saved")
            return redirect('/computer_list')
            # form = ComputerForm()
            # context = {'form':form}
            # return render(request,'computer_entry.html',context)
        else:
            return HttpResponse("missed some Value")
    else:
        form = ComputerForm()
        context = {'form':form}
        return render(request,'computer_entry.html',context)

def computer_list(request):
    queryset = Computer.objects.all()
    form = ComputerSearchForm(request.POST)
    context = {'queryset':queryset,'form':form}
    if request.method == "POST":
        queryset = Computer.objects.all().order_by('.timestamp').filter(computer_name__icontains=form['computer_name'].value(), users_name__icontains = form['users_name'].value())
        context = {'queryset':queryset,'form':form}
        if form['export_to_CSV'].value() == True:
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="Computer list.csv"'
            writer = csv.writer(response)
            writer.writerow(['COMPUTER NAME', 'IP Address', 'MAC ADDRESS','USERNAME', 'LOCATION','PRICE', 'PURCHASE DATE','TIMESTAMP'])
            instance = queryset
            for row in instance:
                  writer.writerow([row.computer_name, row.IP_address, row.MAC_address,row.users_name,row.location,row.price ,row.purchase_date, row.timestamp])
            return response
    return render(request,'computer_list.html',context)
def computer_list_update(request,pk):
    computer = Computer.objects.get(id=pk)
    form = ComputerForm(instance=computer)
    if request.method == "POST":
        form = ComputerForm(request.POST,instance=computer)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Data Saved")
            return redirect('/computer_list')
    else:
        context = {'form':form}
        return render(request,'computer_entry.html',context)

def computer_list_delete(request,pk):
    computer = Computer.objects.get(id=pk)
    computer.delete()
    return redirect('/computer_list')

def registration_view(request):
    form = CreateUserForm()
    context = {'form':form}
    if request.method =="POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            messages.success(request, "Successfully Account is Created for", username)
            return redirect('/login')
        else:
            return redirect('register')
    else:
        return render(request,'registrations.html',context)

def loginpage_view(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.warning(request,"Username or Password Worng")
    return render(request,'loginpage.html')

def logoutpage_view(request):
    logout(request)
    return redirect('/')

def computer_history_list(request):
    title = 'Update history'
    queryset = ComputerHistory.objects.all()
    context = {
       "title": title,
       "queryset": queryset,
    }
    return render(request, "computer_history_list.html",context)


def computer_history_list_delete(request,id):
    computer = ComputerHistory.objects.get(pk=id)
    computer.delete()
    return redirect('computer_history_list')

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>

  <body>
    {% include 'navbar.html' %}
   <main role="main" class="container">
      <div class="jumbotron bg-info">
      <div class="row">
          <div>
                <h1 id="h11" class="text-center font-weight-bold text-danger">This is My Project</h1>
                <p class="h11 lead text-center font-weight-bold">This is our Home Page</p>
              {% if request.user.is_authenticated %}
              <h1 class="h11 text-danger">Welcome to my New Project</h1>
                  <div class="col-md-12">
                  <img style="width:100%" src="/static/img/img11.jpg">
                  </div>
                  {% else %}
                  <center><a class="btn btn-lg btn-primary text-center" href="{% url 'login' %}" role="button">Login</a></center>
              {% endif %}
          </div>
          <div class="col-sm-4">
               {% block content %}
                {% endblock %}
          </div>
      </div>
      </div>

    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js"%}""><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>

templates/computer_entry.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>

  <body>
  {% include 'navbar.html' %}
  <main role="main" class="container">
      <div class="jumbotron">
         <div class="row">
             <div class="col-sm-4">
                 <h1 class="h11"> Add Computer Entry</h1>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}<br>
                            <input type="submit" value="Submit" class="btn btn-success">
                            <input type="reset" value="Clear" class="btn btn-danger">
                    </form>
             </div>
             <div class="col-sm-8">
               <img style="width: 100%" src="/static/img/img11.jpg">
             </div>
         </div>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js"%}""><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>

templates/computer_history_list.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>

  <body>
    {% include 'navbar.html' %}
   <main role="main" class="container">
      <div class="jumbotron bg-warning">
{#      {% if messages %}#}
{#        <ul class="messages">#}
{#               {% for message in messages %}#}
{#                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#                         {{ message }}#}
{#                     </li>#}
{#               {% endfor %}#}
{#       </ul>#}
{#{% endif %}#}
       <h1 class="h11 text-center">Computer History List</h1>
        <table class="table table-bordered table-danger text-center">
            <thead>
            <tr>
                <th>Sr.No</th>
                <th>Computer Name</th>
                <th>IP Address</th>
                <th>MAC Address</th>
                <th>User Name</th>
                <th>Locations</th>
                <th>Price</th>
                <th>Purchase Date</th>
                <th>TimeStamp</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
            <tr>
                <td>{{ item.id }}</td>
                <td><a href="{% url 'computer_list_update' item.id %}"/>{{ item.computer_name }}</td>
                <td>{{ item.IP_address }}</td>
                <td>{{ item.MAC_address }}</td>
                <td>{{ item.users_name }}</td>
                <td>{{ item.location }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.purchase_date }}</td>
                <td>{{ item.timestamp }}</td>
                <td>
                    {% if perms.djangoapp.change_computer %}
                    <a  href="{% url 'computer_list_update' item.id %}"
                        data-toggle="tooltip" title="Update This Item" class="btn btn-success">Update</a>
                        {% else %}
                        <a class="btn btn-info">Update</a>
                        {% endif %}

                    <a href="{% url 'history_delete' item.id %}"
                       data-toggle="tooltip" title="Delete This Item" class="btn btn-danger">Delete</a>

                </td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js"%}""><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>

templates/computer_list.html
 {%  load staticfiles %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>

  <body>
    {% include 'navbar.html' %}
   <main role="main" class="container">
      <div class="jumbotron bg-warning">
      {% if messages %}
        <ul class="messages">
               {% for message in messages %}
                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                         {{ message }}
                     </li>
               {% endfor %}
       </ul>
{% endif %}
       <h1 class="h11 text-center">Computer Entry List</h1>
      <div class="search-flt">
      <form method = "POST">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Search" class="btn btn-danger">
      </form>
      </div>
        <table class="table table-bordered table-danger text-center">
            <thead>
            <tr>
                <th>Sr.No</th>
                <th>Computer Name</th>
                <th>IP Address</th>
                <th>MAC Address</th>
                <th>User Name</th>
                <th>Locations</th>
                <th>Price</th>
                <th>Purchase Date</th>
                <th>TimeStamp</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
            <tr>
                <td>{{ item.id }}</td>
                <td><a href="{% url 'computer_list_update' item.id %}"/>{{ item.computer_name }}</td>
                <td>{{ item.IP_address }}</td>
                <td>{{ item.MAC_address }}</td>
                <td>{{ item.users_name }}</td>
                <td>{{ item.location }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.purchase_date }}</td>
                <td>{{ item.timestamp }}</td>
                <td>
                    {% if perms.djangoapp.change_computer %}
                    <a  href="{% url 'computer_list_update' item.id %}"
                        data-toggle="tooltip" title="Update This Item" class="btn btn-success">Update</a>
                        {% else %}
                        <a class="btn btn-info">Update</a>
                        {% endif %}

                        {% if perms.djangoapp.delete_computer %}
                    <a href="{% url 'computer_list_delete' item.id %}"
                       data-toggle="tooltip" title="Delete This Item" class="btn btn-danger">Delete</a>
                    {% else %}
                     <a class="btn btn-warning">Delete</a>
                     {% endif %}

                </td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js"%}""><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  </body>
</html>

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet"/>
</head>
<body>
{{ title }}
</body>
</html>

templates/loginpage.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<div class="container1 text-left">
    <div class="row">
        <div class="offset-md-6 col-md-6">

            <form method="POST">
                <h2 class="text-center mt-5 bg-primary text-white">Login Page</h2>
                {% csrf_token %}
                <lable>Username:</lable>
                <input type="text" name="username" class="form-control">

                <lable>Password:</lable>
                <input type="password" name="password" class="form-control">
            <br>
                <center>
                <input type="submit" value="Login" class="btn btn-danger">
                </center>
            <br>
                {% for i in messages %}
                <p id="p11">{{ i }}</p>
                {% endfor %}
                <h3>Create New Account:<a class="btn btn-success" href="{% url 'register' %}">SingUp</a></h3>
            </form>

        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Navbar</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Computer Inventory Managment System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'computer_list' %}">Computer List</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'computer_entry' %}">Computer Entry</a>
          </li>
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'computer_history_list' %}">Computer history</a>
            </li>
            {% endif %}
        </ul>
          {% if request.user.is_authenticated %}
              <li><a class="" href="{% url 'logout' %}"><button class="btn btn-danger">{{ user }} | Logout</button></a> </li>
          {% else %}
          <li><a href="{% url 'login'%}">Login</a> </li>
          {% endif %}
{#        <form class="form-inline mt-2 mt-md-0">#}
{#          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">#}
{#          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#        </form>#}
      </div>
    </nav>
</body>
</html>

templates/registrations.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrations Page</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<div class="container">
    <div class="row">
        <div class="offset-md-8 col-md-12">
            <h1 class="h11 text-primary text-center bg-dark">Registration Form</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy}}
    <center>
        <input type="submit" value="Register" class="btn btn-danger">
    </center>
</form>

        </div>
    </div>
</div>
{% endblock %}
</body>
</html>